### ISSUE TITLE
Highstocks Annotation: Problem with rect width when units is value 

### ISSUE THREAD

**Issue by mostafa-v** [blacklabel/annotations#22]
I want to draw a rectangle around a double top pattern in chart. As you see in the jsfiddle, there is a list of points (zigzag) and we want to draw a circle around point 3 to point to point 7. so i find minimum and maximum x and y, and calculate width and height. the height is working as it should, but the width is not correct and also changes randomly when scrolling or resizing.

http://jsfiddle.net/tLgzv9u6/

**Comment by pawelfus** [comment]
It's caused by using `ordinal` xAxis, workaround is to disable that option: http://jsfiddle.net/tLgzv9u6/1/

**Comment by pawelfus** [comment]
From now, to get properly calculated values for ordinal Axis (and while using units), we need to specify `x` and `y` values, so in your case:

    annotations: [{
        anchorX: "left",
        anchorY: "bottom",
        x: 0,
        y: 0,
        shape: {
            units: "values",
            type: "rect",
            params: {
                x: minX,
                y: minY,
                width: (maxX - minX),
                height: (maxY - minY),
                stroke: "red"
            }
        }
    }]

Example: http://jsfiddle.net/tLgzv9u6/3/

**Comment by mostafa-v** [comment]
Thank you very much!
