### ISSUE TITLE
Drag not working for other than first chart

### ISSUE THREAD

**Issue by rakeshpant** [blacklabel/annotations#23]
First of all thanks for creating this plugin, its really very useful.

I have a need to create a dashboard with multiple charts and allow annotations on the fly. 
I have used this plugin, but one problem I am struggling with is - when I add more than one chart on a single page, then dragging of annotations work for only first chart, it doesn't work for other charts.
Could you please give me some pointers to get over this issue?

Thanks Once Again!

**Comment by pawelfus** [comment]
Sound like an issue with CSS, probably something overlaps your chart. Check DOM in dev tools.

**Comment by rakeshpant** [comment]
Well, as a temporary workaround for me I have commented out following lines in translateAnnotation method -
//	if (!chart.isInsidePlot(clickX - chart.plotLeft, clickY - chart.plotTop)) {
					//		return;
					//	}

Apparently, under certain circumstances, plot boundaries are not being calculated properly.

**Comment by pawelfus** [comment]
If you remove annotations and just enable zooming in/out by mouse, then does it work? I'm curious, because `isInsidePlot()` method is built-in function in Highcharts core.

**Comment by rakeshpant** [comment]
Yes, zoom in/out works fine in all the charts.
