### ISSUE TITLE
Is it possible to annotate the Navigator

### ISSUE THREAD

**Issue by ecurtis** [blacklabel/annotations#25]
I have a project were I would like to put some time based labels in the navigator of highStock (calling out historical events like the Tech Bubble etc). Any advice would be appreciated. Cheers.

**Comment by pawelfus** [comment]
You need to inform annotations which y/xAxis are used. For example: http://jsfiddle.net/7m3Mr/72/ (second axes belongs to navigator, and axes in Highcharts are indexed from 0). 

However, wouldn't be easier just to use flag series in that navigator?

**Comment by ecurtis** [comment]
Thank you. Both suggestions are very helpful. This is my first highchart project so the flag series was new to me.
