### ISSUE TITLE
Toggle annotation buttons

### ISSUE THREAD

**Issue by RyanRusnak** [blacklabel/annotations#28]
Is it possible to toggle the annotation buttons? This feature would help a lot of users. I am happy to make a PR if someone can point me in the right direction.

**Comment by pawelfus** [comment]
Do you mean to show/hide buttons by some function?

**Comment by pawelfus** [comment]
Simple snippet to achieve above: http://jsfiddle.net/7m3Mr/73/

        $.each(chart.annotations.buttons, function(i, button) {
            button[0].hide(); // or show()
            button[1].hide(); // or show()
        });

**Comment by RyanRusnak** [comment]
That is absolutely fantastic. Would you like me to make a PR to update the README?

**Comment by pawelfus** [comment]
I'm not sure if this is necessary? It's just simple DOM operation, possible to achieve in many ways, above one is just an example.

**Comment by RyanRusnak** [comment]
OK, either way, thanks for the help and plugin!
