### ISSUE TITLE
How does someone draw a straight line annotation?

### ISSUE THREAD

**Issue by feugatos** [blacklabel/annotations#29]
Hi,

I stumbled upon Annotations for Highcharts. The documentation is pretty good but I'm having trouble creating an annotation that is just a straight line (aka path).

I really can't understand how the xValue, xValueEnd and params.d parameter work for path annotations.

Could someone edit this jsfiddle http://jsfiddle.net/7m3Mr/78/ so that a straight line is drawn starting at xValue: 2, ending at xValueEnd: 6 and at height of yValue: 2?

Alternatively could someone provide better documentation for params.d for paths?

Thanks in advance,
Dimitris.

**Comment by pawelfus** [comment]
It's the same issue as #24, example for you: http://jsfiddle.net/7m3Mr/79/

In fact, `units: "values"` should take care of that kind of paths. Using `x/yValueEnd` works only for straight lines. 

So in short:

- set empty path, e.g. `d: ['M', 0, 0, 'L', 0, 0]`
- set all params `xValue`, `xValueEnd`, `yValue` and `yValueEnd`

**Comment by pawelfus** [comment]
Fixed in last commit, see: http://jsfiddle.net/7m3Mr/84/
