### ISSUE TITLE
Wrong Lane position if chart rendered under a div has style position:relative;

### ISSUE THREAD

**Issue by nosensezzz** [blacklabel/annotations#32]
<h3>Wrong Position</h3>
<div style="margin: 10px 0px 50px 0px;width: 854px; float: left;position:relative">
		<div id="container" style="float: left; height: 542px; width: 800px;left:0;position:absolute;">
		</div>
</div>

if I load chart under a div that has attribute{ position:relative;  margin or padding }, the innotation line will display at wrong position, does anyone know how to fix this issue?

**Comment by pawelfus** [comment]
Could you create jsFiddle with that issue? We will check this.

**Comment by chalexIAC** [comment]
Hi!
I had the same problem, 
solved it for my app  by calculating all parents offsets 


for example
getRadius: function(e) {
                        /*ch*/
            var offsetX = 0, offsetY  = 0;
            var curelem = this.chart.container;
            while(curelem.offsetParent){
                curelem  = curelem.offsetParent;
                offsetX += curelem.offsetLeft;
                offsetY += curelem.offsetTop;
            }
            /**/
		var ann = this,
			chart = ann.chart,
			x = e.pageX - offsetX,
			y = e.pageY - offsetY,
			xAxis = chart.xAxis[ann.options.xAxis],
			yAxis = chart.yAxis[ann.options.yAxis],
			dx = Math.abs(x - xAxis.toPixels(ann.options.xValue)),
			dy = Math.abs(y - yAxis.toPixels(ann.options.yValue));
			radius = parseInt(Math.sqrt(dx * dx + dy * dy), 10);
		ann.shape.attr({
			r: radius
		});
		return radius;
	}

**Comment by pawelfus** [comment]
Live demo: http://jsfiddle.net/7m3Mr/96/

Applies only when adding annotations by buttons.

**Comment by pawelfus** [comment]
Should be fixed, could you confirm?

**Comment by chalexIAC** [comment]
works fine! thnks!

**Comment by nosensezzz** [comment]
sorry , reply you so late, I wasn't get back to this project lately.

but, it did works properly now, thank you!
