### ISSUE TITLE
buttons move onto export button

### ISSUE THREAD

**Issue by chalexIAC** [blacklabel/annotations#34]
may be I miss some settings 
here the example
http://jsfiddle.net/chalex/q8u529rf/

**Comment by pawelfus** [comment]
This is a little problematic, let's consider this example: http://jsfiddle.net/q8u529rf/1/ - where title is enabled. We would need to implement collision detection for buttons or check for the size of the title. None of that solutions sounds good - first one is to big, second one may create another issues, for example when setting `chart.marginTop`. Do you have any suggestion?

Another way out may be to allow user set `offset` for the buttons group - how does it sound? Not universal, but allows to avoid such problems.

**Comment by chalexIAC** [comment]
allowing user to set offset for the buttons it's a great solution. thank you!

**Comment by pawelfus** [comment]
Added `anntationsOptions.buttonsOffsets` option, to set array of the offsets: `[x, y]`. Let us know if you find any issues with that.
