### ISSUE TITLE
How we can edit the title on annotation

### ISSUE THREAD

**Issue by pranjalps03** [blacklabel/annotations#37]

**Comment by pawelfus** [comment]
Use `annotation.update()`.

**Comment by pranjalps03** [comment]
I want to update the title like of contentediatble=true or wheather I could inject the id on <tspan> in svg.

**Comment by pranjalps03** [comment]
I want to update the title like of contenteditable=true or wheather I could inject the id on <tspan> in svg.

**Comment by pranjalps03** [comment]
I want to update the title like of contentediatble=true or wheather I could inject the id on tspan in svg.

**Comment by pawelfus** [comment]
I'm not sure, but is condentEditable supported in SVG? I made simple test case:  http://jsfiddle.net/7m3Mr/136/ - doesn't work.

And regarding ID's, you can add ID to the annotation text using `element.attr()`, see: http://jsfiddle.net/7m3Mr/137/

**Comment by pawelfus** [comment]
Or example to set title.id in options: http://jsfiddle.net/7m3Mr/138/
