### ISSUE TITLE
how to use { 	annotationEvents: { 		step: callback,  		stop: callback  	},

### ISSUE THREAD

**Issue by pranjalps03** [blacklabel/annotations#38]

**Comment by pawelfus** [comment]
Use them as standard callback to update annotation. For example, when adding circle, update radius. When creating rectangle, update width/height/x/y etc.

Here you can find example how it's implemented with built-in buttons:

- https://github.com/blacklabel/annotations/blob/master/js/annotations.js#L72
- https://github.com/blacklabel/annotations/blob/master/js/annotations.js#L88
