### ISSUE TITLE
How to put break in the text after I changing the annotation title runtime

### ISSUE THREAD

**Issue by pranjalps03** [blacklabel/annotations#41]

**Comment by pawelfus** [comment]
Use `<br>`in a place where you want to add break.

**Comment by pranjalps03** [comment]
But <br> give me error...... other tags are working perfectly except <br>

**Comment by pawelfus** [comment]
Please, recreate issue on the jsfiddle, I will check this.

**Comment by pawelfus** [comment]
No answer since 21+ days, closing. Please reopen when you recreate issue on jsfiddle or something similar.
