### ISSUE TITLE
How to delete an annotation?

### ISSUE THREAD

**Issue by kumaresanm** [blacklabel/annotations#46]
After I drag and drop a square box, is it possible to delete it?
![anno](https://cloud.githubusercontent.com/assets/5888338/10330190/9aafc456-6ce7-11e5-825d-b9e957491769.JPG)

**Comment by sebastianbochan** [comment]
In case when you would like to add delete action you should disable default buttons and create your own by options available in annotations plugin. In each button you can define an action (like double click) to remove shape. Important thing is that buttons require to call step / stop events, which should set in code. (source of them are available in annotation source code).

Example: 
- http://jsfiddle.net/7m3Mr/163/

**Comment by kumaresanm** [comment]
Thank you @sebastianbochan . It works for me..

**Comment by kumaresanm** [comment]
Hello @sebastianbochan ,
Is it able to save the Annotation in the chart.? So that if I share the chart to someone, even he should be able to see it.
