### ISSUE TITLE
Is it possible to save the annotation?

### ISSUE THREAD

**Issue by kumaresanm** [blacklabel/annotations#47]
If I share the chart with some one he should also be able to see the annotation that I have created.

**Comment by pawelfus** [comment]
Sorry for a late reply! Yes, of course this is possible. Simply store all created annotations-options from `chart.annotations.allItems[index].options`, for example:
 
    var annotations = [];
    $.each(chart.annotations.allItems, function(i, ann) {
      annotations.push(ann.options);
    });

Now just save your data in your database with connected chart. Later, when loading chart, load annotations from the database and create chart with them.
