### ISSUE TITLE
Annotation with linkedTo not positioned correctly if multiple series on non line chart

### ISSUE THREAD

**Issue by dugokontov** [blacklabel/annotations#48]
When chart has multiple series, annotation with `linkedTo` property is not positioned correctly if chart type is not line/area chart, or if it is stacked.

Here is example of column chart with multiple series, where annotation is not positioned correctly:

http://jsfiddle.net/hy6vu21f/

**Comment by pawelfus** [comment]
Indeed, looks like when `grouping` is used, `linkedTo` option doesn't consider offset for columns.
