### ISSUE TITLE
Add a call to select annotation

### ISSUE THREAD

**Issue by priikone** [blacklabel/annotations#50]
It would be nice to be able to add new annotation with addAnnotation and have it already selected and/or have a call to select a specific annotation.

**Comment by pawelfus** [comment]
Good idea! For now you can use this snippet:

    annotation.events.storeAnnotation(e, annotation, chart);
    annotation.events.select(e, annotation, false);

First one stores references to the annotation (for drag&drop etc), and second one renders dashed border around the annotation.

**Comment by priikone** [comment]
Great, thanks, I shall be using that workaround for now.
