### ISSUE TITLE
Downloading image of chart with exporting plugin broken

### ISSUE THREAD

**Issue by samidabeast** [blacklabel/annotations#74]
When I add the exporting plugin to download an image of the chart with annotations it turns everything black. Simply printing works just fine, but not any of the downloads.

**Comment by pawelfus** [comment]
Could you setup a live demo with this issue? This looks fine: https://jsfiddle.net/7m3Mr/367/

Note: Our demos use CSS version of Highcharts, so this is correct js-file for our demos: https://code.highcharts.com/js/modules/exporting.js

**Comment by samidabeast** [comment]
I was working off your demos so that might have been why. I'll add it to my chart in my project to make sure though.
