### ISSUE TITLE
Click event is not working on annotation label in pie chart using highcharts?

### ISSUE THREAD

**Issue by dheerajraja111** [blacklabel/annotations#76]
Click event is not working on annotation label in highcharts? to Click event is not working on annotation label in pie chart using highcharts?

**Comment by KacperMadej** [comment]
Hi @dheerajraja111 ,

Please add a live demo for the problem.

**Comment by pawelfus** [comment]
Closing the issue. If someone will be able to recreate the issue, please let us know.
