### ISSUE TITLE
Circular icon over the arc of donut chart 

### ISSUE THREAD

**Issue by dheerajraja111** [blacklabel/annotations#77]
Is it possible to set circular icon over the arc of donut chart using Highcharts? something like this...https://imgur.com/yKhWKOu

**Comment by pawelfus** [comment]
Hi @dheerajraja111 

It's possible to add images to a chart using Highcharts.Renderer class: https://api.highcharts.com/class-reference/Highcharts.SVGRenderer#image . Unfortunately, our annotations plugin won't help you achieve this design.

**Comment by dheerajraja111** [comment]
Thanks, I've one query regarding annotations. Is it possible to add events
on annotations? If possible, could you please share an example.
Thanks in advance

**Comment by KacperMadej** [comment]
Annotations already have events added - for selection state after click. Demo: http://blacklabel.github.io/annotations/

Please check the code for more information - e.g. [this part](https://github.com/blacklabel/annotations/blob/master/js/annotations.js#L508-L518).

More about adding events can be found in [Highcharts documentation for the `addEvent` function](https://api.highcharts.com/class-reference/Highcharts#addEvent).

**Comment by dheerajraja111** [comment]
I am trying the same thing, but it is not working. Do we need to add any
other plugin for it except 'annotation.js'?

**Comment by dheerajraja111** [comment]
The below thing I'm trying, but it's not working. Could you please look
over it or guide me with some other example??



annotations: [{
events:{
click: function(){
alert("fhf");
}
},
labels: [{
point: '0',
shape: 'callout',
y: -120,
backgroundColor: 'red',
useHTML: true,
formatter: function() {
return '<button class="donut-info" type="button"
onclick="window.localStorage.setItem(`infoClick`, `true`);">i</button><span
id="ab" value="'+ this.y+'">' +this.name+ '<br>'+ '$'+ this.y+'</span>'
//console.log(this.series.data.indexOf(this));
//return "<span id='ab' style='cursor: pointer'>" +this.name + '<br>' + "$"
+ this.y+ "</span>"
}

},

-- 
Regards,
Dheeraj Raja

**Comment by KacperMadej** [comment]
annotations.labels is not an option in this plugin - this is a option for Highcharts official module: https://api.highcharts.com/highstock/annotations.labels

Please decide which one are you trying to use - this plugin or the official module. In case of the module contact Highcharts support: https://www.highcharts.com/support

If you could post a live demo next time it would help us avoid the confusion.

Here's a demo for plugin with click event: http://jsfiddle.net/BlackLabel/rchm4ek5/
