### ISSUE TITLE
HIGHSTOCK 6.1.0 Can't used Annotations 

### ISSUE THREAD

**Issue by ghost** [blacklabel/annotations#79]
I download it in :
https://www.highcharts.com/download

and the module Annotations can't used.

**Comment by pawelfus** [comment]
Hi @szargv 

Annotations are supported by core library, you don't need to use this plugin: https://www.highcharts.com/docs/advanced-chart-features/annotations-module

Just in case: http://blacklabel.github.io/annotations/ - this version uses v6.1.0 and works fine so our plugin still works.
