### ISSUE TITLE
The annotations module cannot achieve

### ISSUE THREAD

**Issue by gypjoy** [blacklabel/annotations#82]
"highcharts": "^6.1.0",
"highcharts-annotations": "^1.3.3",

import Highcharts from 'highcharts'
import HighchartsAnnotations from 'highcharts-annotations'
HighchartsAnnotations(Highcharts)

let chartOptions = {
chart: {
annotations: [{
          xValue: 4,
          yValue: 125,
          title: {
            text: 'Annotated chart!'
          },
          events: {
            click: function (e) { console.log('Annotation clicked:', this) }
          }
        }],
}
this.chart = this.$highcharts.chart('divId', chartOptions) 

vue.esm.js:1741 ReferenceError:   $ is not defined
    at Annotation.render (annotations.js:545)
    at a.Chart.addAnnotation (annotations.js:982)
    at a.Chart.<anonymous> (annotations.js:1074)
    at a.Chart.<anonymous> (highcharts.js:266)

**Comment by KacperMadej** [comment]
Hi @gypjoy 

Thank you for reporting about the problem.

I would love for the annotations module to achieve.

Unfortunately, [Annotations are a part of Highstock 6+ and Highcharts 6+ as a module. This plugin was build for older versions of Highstock.](https://github.com/blacklabel/annotations#-annotations-are-a-part-of-highstock-6-and-highcharts-6-as-a-module-this-plugin-was-build-for-older-versions-of-highstock)

Here's more info about the module: https://www.highcharts.com/docs/advanced-chart-features/annotations-module
