### ISSUE TITLE
The annotations are not showing up in the chart with X-Axis as DateAxis.

### ISSUE THREAD

**Issue by Anudeep-Kadavergu** [blacklabel/annotations#83]
Here I am attaching the live demo [Live Demo](https://jsfiddle.net/Anudeep001/9bov51na/19/)

Problem:
I want to add shapes (rectangles) based on start and end values (datetime).

Please refer the above fiddle

**Comment by KacperMadej** [comment]
Hi @Anudeep-Kadavergu 

Annotations are a part of Highstock 6+ and Highcharts 6+ as a module. This plugin was built for older versions of Highstock.

Annotations could be added using API options. See related API reference: https://api.highcharts.com/highcharts/annotations

For technical support see https://www.highcharts.com/blog/support/

**Comment by Anudeep-Kadavergu** [comment]
Oh ok, Thank you
